### ISSUE TITLE
Add feature to overwrite input file and process multiple files, for easy batch processing.

### ISSUE THREAD

**Issue by damian101** [Traneptora/umbrielpng#1]
Overwriting the input with `-o` is already possible, so this functionality should be easy to implement. However, what makes it a little more complicated is that a specified output with `-o` is obviously incompatible with multiple specified sources, and would therefore in combination need to prompt an error message.

**Comment by Traneptora** [comment]
What happens if you use `--fix` and then specify multiple input files?

**Comment by damian101** [comment]
Waaait, `--fix` already does what I want, also allows batch processing.
Maybe should be renamed to something more descriptive, like `--in-place`...

**Comment by Traneptora** [comment]
That's not a bad idea, perhaps `--fix-in-place` could work.
